// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataContext.Migrations
{
    [DbContext(typeof(CustomerServiceContext))]
    [Migration("20260224164739_A_Customer_Service")]
    partial class A_Customer_Service
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.Call", b =>
                {
                    b.Property<int>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallId"));

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CallId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Repository.Entities.CallParticipantAnalysis", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<double?>("AvgVolume")
                        .HasColumnType("float");

                    b.Property<int>("CallId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ImprovementNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("PeakVolume")
                        .HasColumnType("float");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Transcript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WordsPerSecond")
                        .HasColumnType("float");

                    b.HasKey("ParticipantId");

                    b.HasIndex("CallId");

                    b.HasIndex("OperatorId");

                    b.ToTable("CallParticipantAnalyses");
                });

            modelBuilder.Entity("Repository.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IntroPhrase")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Repository.Entities.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperatorId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<double?>("DailyScore")
                        .HasColumnType("float");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MonthlyScore")
                        .HasColumnType("float");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperatorId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Repository.Entities.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<double?>("AvgVolumeScore")
                        .HasColumnType("float");

                    b.Property<int>("CallId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("float");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<double?>("PeakVolumeScore")
                        .HasColumnType("float");

                    b.Property<double?>("WordsPerSecondScore")
                        .HasColumnType("float");

                    b.HasKey("ScoreId");

                    b.HasIndex("CallId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Repository.Entities.Call", b =>
                {
                    b.HasOne("Repository.Entities.Company", "Company")
                        .WithMany("Calls")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Repository.Entities.CallParticipantAnalysis", b =>
                {
                    b.HasOne("Repository.Entities.Call", "Call")
                        .WithMany("CallParticipants")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Operator", "Operator")
                        .WithMany("ParticipantAnalyses")
                        .HasForeignKey("OperatorId");

                    b.Navigation("Call");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Repository.Entities.Operator", b =>
                {
                    b.HasOne("Repository.Entities.Company", "Company")
                        .WithMany("Operators")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Repository.Entities.Score", b =>
                {
                    b.HasOne("Repository.Entities.Call", "Call")
                        .WithMany("Scores")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Repository.Entities.CallParticipantAnalysis", "Participant")
                        .WithMany("Scores")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Repository.Entities.Call", b =>
                {
                    b.Navigation("CallParticipants");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Repository.Entities.CallParticipantAnalysis", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Repository.Entities.Company", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("Operators");
                });

            modelBuilder.Entity("Repository.Entities.Operator", b =>
                {
                    b.Navigation("ParticipantAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
